create table if not exists public.orders_from_tsv (
  id bigint generated by default as identity primary key,
  order_id text,
  order_date timestamptz,
  return_request_date timestamptz,
  label_cost numeric,
  return_carrier text,
  tracking_id text not null,
  merchant_sku text,
  order_amount numeric,
  fedex_status jsonb,
  manual_status text,
  created_at timestamptz default now()
);

create index if not exists idx_orders_tracking on public.orders_from_tsv(tracking_id);
